{"trial_id": "0", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "conv_1_filtter", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 16, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "conv_1_kernel", "default": 3, "conditions": [], "values": [3, 5], "ordered": true}}, {"class_name": "Choice", "config": {"name": "max_1", "default": 2, "conditions": [], "values": [2, 3, 5], "ordered": true}}, {"class_name": "Int", "config": {"name": "conv_2_filter", "default": null, "conditions": [], "min_value": 48, "max_value": 64, "step": 8, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "max_2", "default": 2, "conditions": [], "values": [2, 3, 5], "ordered": true}}, {"class_name": "Int", "config": {"name": "dense_1", "default": null, "conditions": [], "min_value": 64, "max_value": 128, "step": 8, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001], "ordered": true}}], "values": {"conv_1_filtter": 128, "conv_1_kernel": 5, "max_1": 2, "conv_2_filter": 64, "max_2": 5, "dense_1": 96, "learning_rate": 0.001}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n            ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 155, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_17796\\4191296390.py\", line 2, in model_building\n    model=Sequential([\n          ^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\keras\\src\\models\\sequential.py\", line 74, in __init__\n    self._maybe_rebuild()\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\keras\\src\\models\\sequential.py\", line 139, in _maybe_rebuild\n    self.build(input_shape)\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\keras\\src\\layers\\layer.py\", line 223, in build_wrapper\n    original_build_method(*args, **kwargs)\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\keras\\src\\models\\sequential.py\", line 183, in build\n    x = layer(x)\n        ^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\keras\\src\\ops\\operation_utils.py\", line 221, in compute_conv_output_shape\n    raise ValueError(\nValueError: Computed output size would be negative. Received `inputs shape=(None, 62, 62, 128)`, `kernel shape=(64, 64, 128, 64)`, `dilation_rate=[1 1]`.\n"}